"""add nullable user_id to projects

Revision ID: 2f341135eb58
Revises: 4b789a04768d
Create Date: 2026-09-23 06:53:29.527710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f341135eb58'
down_revision: Union[str, Sequence[str], None] = '4b789a04768d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.UUID(), nullable=True))
    # 自動生成された無名の外部キーはdowngradeで削除できないため、明示的に命名する。
    op.create_foreign_key('fk_projects_user_id_users', 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_user_id_users', 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
